### ISSUE TITLE
backendとしてAzure Blob Storageなどを使うようにしたい

### ISSUE THREAD

**Issue by os1ma** [GenerativeAgents/dify-azure-terraform#3]
#### 課題1. tfstateファイルを誤って削除する可能性がある

現状では、terraform apply実行後、tfstateファイルがローカルに作成されると思います。
もしも作成されたtfstateファイルを削除してしまったりすると、リソースの更新・削除などを適切に行うのが困難になってしまいます。
そこで、tfstateを誤って削除しような手順にしたいです。

#### 課題2. パスワードなどのセンシティブな情報が書かれたtfstateファイルがローカルに配置される 

現状の実装では、tfstateファイルにパスワードなどのセンシティブな値が記載されます。
そのtfstateファイルをローカルではなくAzure Blob Storageなどで管理したほうがよりよさそうです。

※理想的にはtfstateファイルにセンシティブな値を書き込まないという手法もありますが、まずはtfstateファイルをAzure Blob Storageなどで管理する対応でもよさそうです。

### 対応案

Terraformでは、tfstateの保存先としてbackendを設定できます。
Azureを使用しているので、Azure Blob Storageをbackendにするのがよさそうです。

以下が参考になりそうです。

- https://developer.hashicorp.com/terraform/language/backend/azurerm
- https://learn.microsoft.com/ja-jp/azure/developer/terraform/store-state-in-azure-storage?tabs=azure-cli

たとえば以下のような手順になりそうです。

1. リソースグループを手作業で作成
2. Azure Blob Storageを手作業で準備
3. terraform init・plan・apply

### 優先度

緊急ではないですが、tfstateを誤って削除するようなことが起こる前に対応できるとよさそうです。

こちらのIssueに対応できるまでは、READMEに「tfstateファイルを削除ように」といった注意書きがあるといいかもしれません。

**Comment by tubone24** [comment]
対応済み
