### ISSUE TITLE
動作確認したterraformコマンドのバージョンを明記しておきたい

### ISSUE THREAD

**Issue by os1ma** [GenerativeAgents/dify-azure-terraform#4]
terraformコマンドのバージョンアップによりうまく実行できなくなるケースを回避したいので、terraformコマンドのバージョンを明記しておきたいです。

### 対応案

以下のどちらかの対応がよさそうです。（両方でもいいかもしれません）

- 対応案1.）required_versionを記述する
  - 参考: https://dev.classmethod.jp/articles/about-terraform-version-required-constraints/
- 対応案2）tfenvなどの設定ファイル（.terraform-version）を配置する

### 優先度

緊急ではないですが、それほど大変な内容ではないので早めに対応しておくとよさそうです。

簡易的な対応として、動作確認したterraformコマンドのバージョンをREADMEに書いておく程度でもいいかもしれません。

**Comment by tubone24** [comment]
対応済み
